[workspace]
members = ["sm4sh_lib", "sm4sh_model", "sm4sh_test"]
resolver = "2"

[workspace.dependencies]
bilge = "0.2.0"
binrw = "0.14.1"
half = "2.4.1"
clap = {version = "4.5.28", features = ["derive"] }
rayon = "1.10.0"