[package]
name = "sm4sh_shader"
version = "0.1.0"
edition = "2024"

[dependencies]
sm4sh_model = { path = "../sm4sh_model" }
nom = "8.0.0"
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
