// Include the bindings generated by build.rs.
// Not modifying the src directory makes this crate easier to publish.
#[allow(dead_code)]
pub mod blit {
    include!(concat!(env!("OUT_DIR"), "/blit.rs"));
}
#[allow(dead_code)]
pub mod bloom_add {
    include!(concat!(env!("OUT_DIR"), "/bloom_add.rs"));
}
#[allow(dead_code)]
pub mod bloom_blur_combine {
    include!(concat!(env!("OUT_DIR"), "/bloom_blur_combine.rs"));
}
#[allow(dead_code)]
pub mod bloom_blur {
    include!(concat!(env!("OUT_DIR"), "/bloom_blur.rs"));
}
#[allow(dead_code)]
pub mod bloom_bright {
    include!(concat!(env!("OUT_DIR"), "/bloom_bright.rs"));
}
#[allow(dead_code)]
pub mod bone {
    include!(concat!(env!("OUT_DIR"), "/bone.rs"));
}
#[allow(dead_code)]
pub mod model {
    include!(concat!(env!("OUT_DIR"), "/model.rs"));
}
#[allow(dead_code)]
pub mod variance_shadow {
    include!(concat!(env!("OUT_DIR"), "/variance_shadow.rs"));
}
