// Include the bindings generated by build.rs.
// Not modifying the src directory makes this crate easier to publish.
#[allow(dead_code)]
pub mod bone {
    include!(concat!(env!("OUT_DIR"), "/bone.rs"));
}

#[allow(dead_code)]
pub mod model {
    include!(concat!(env!("OUT_DIR"), "/model.rs"));
}
