[package]
name = "sm4sh_test"
version = "0.1.0"
edition = "2024"

[dependencies]
sm4sh_lib = { path = "../sm4sh_lib" }
sm4sh_model = { path = "../sm4sh_model" }
globwalk.workspace = true
rayon.workspace = true
binrw.workspace = true
clap.workspace = true
